;;; env-ext.el --- Login-shell environment capture -*- lexical-binding: t; -*-
;;; Commentary:
;; Captures environment variables from the login shell and caches them so
;; that GUI Emacs (launched outside a terminal, e.g. via systemd or a desktop
;; launcher) inherits the full shell environment (PATH, GOPATH, NVM_DIR, …).
;;; Code:

(defvar moyu/denied-env-patterns
  '(;; Unix/shell state that shouldn't be persisted
    "^HOME$" "^\\(OLD\\)?PWD$" "^SHLVL$" "^PS1$" "^R?PROMPT$" "^TERM\\(CAP\\)?$"
    "^USER$" "^INSIDE_EMACS$"
    ;; X server, Wayland, or session services
    "^DISPLAY$" "^WAYLAND_DISPLAY" "^DBUS_SESSION_BUS_ADDRESS$" "^XAUTHORITY$"
    ;; Windows / WSL
    "^WSL_INTEROP$"
    ;; XDG runtime-only variables
    "^XDG_CURRENT_DESKTOP$" "^XDG_RUNTIME_DIR$"
    "^XDG_\\(VTNR\\|SEAT\\|SESSION_\\(TYPE\\|CLASS\\)\\)"
    ;; Sockets: I3SOCK, GREETD_SOCK, SEATD_SOCK, SWAYSOCK, …
    "SOCK$"
    ;; SSH / GPG (become stale quickly)
    "^SSH_\\(AUTH_SOCK\\|AGENT_PID\\)$" "^\\(SSH\\|GPG\\)_TTY$" "^GPG_AGENT_INFO$"
    ;; Internal flags
    "^DEBUG$" "^INSECURE$" "^__")
  "Regexps matching env var names to exclude from the env cache file.")

(defun moyu/env--denied-p (var)
  "Return non-nil if VAR matches any pattern in `moyu/denied-env-patterns'."
  (seq-some (lambda (pat) (string-match-p pat var))
            moyu/denied-env-patterns))

(defun moyu/env--shell-environ ()
  "Return a list of \"KEY=VALUE\" strings sourced from the login shell.
Uses NUL-separated output (`env -0') when available so that values
containing newlines are handled correctly.  Falls back to the current
`process-environment' on Windows or when the shell cannot be invoked."
  (if (eq system-type 'windows-nt)
      (default-toplevel-value 'process-environment)
    (let* ((shell (or (getenv "SHELL") "/bin/sh"))
           (quoted (shell-quote-argument shell))
           ;; Try env -0 first (GNU coreutils; safe with embedded newlines)
           (raw0 (condition-case nil
                     (shell-command-to-string
                      (format "%s -l -c 'env -0' 2>/dev/null" quoted))
                   (error nil))))
      (cond
       ((and raw0 (string-match-p "\0" raw0))
        (seq-filter (lambda (s) (string-match-p "=" s))
                    (split-string raw0 "\0" t)))
       ;; Fallback: plain env, newlines in values are unlikely in practice
       (t
        (let ((raw (condition-case nil
                       (shell-command-to-string
                        (format "%s -l -c env 2>/dev/null" quoted))
                     (error ""))))
          (if (string-empty-p raw)
              (progn
                (message "env-ext: could not invoke login shell, \
falling back to process-environment")
                (default-toplevel-value 'process-environment))
            (seq-filter (lambda (s) (string-match-p "=" s))
                        (split-string raw "\n" t)))))))))

(defun generate-env-file (file)
  "Capture the login-shell environment and write it to FILE."
  (let ((vars (moyu/env--shell-environ)))
    (with-temp-file file
      (setq-local coding-system-for-write 'utf-8)
      (insert ";; -*- mode: lisp-interaction; coding: utf-8-unix; -*-\n"
              ";; Auto-generated by env-ext.el — DO NOT EDIT.\n"
              ";; Refresh with M-x moyu/reload-env\n\n"
              "(")
      (dolist (entry vars)
        (unless (moyu/env--denied-p (car (split-string entry "=")))
          (insert (prin1-to-string entry) "\n ")))
      (insert ")")))
  t)

(defun load-env-file (file &optional noerror)
  "Merge environment variables from FILE into the running Emacs session.
New values from FILE take precedence; duplicate keys already present in
`process-environment' are replaced rather than appended, so repeated
calls do not inflate the environment list."
  (if (not (file-exists-p file))
      (unless noerror
        (signal 'file-error (list "No env file" file)))
    (condition-case err
        (with-temp-buffer
          (insert-file-contents file)
          (let ((new-env (read (current-buffer))))
            (when (listp new-env)
              (let* ((new-keys (mapcar (lambda (e) (car (split-string e "=")))
                                       new-env))
                     ;; Keep old entries whose key is not overridden by new-env
                     (old-env (seq-remove
                               (lambda (e)
                                 (member (car (split-string e "=")) new-keys))
                               (default-value 'process-environment)))
                     (merged (append new-env old-env)))
                (setq-default
                 process-environment merged
                 exec-path           (append
                                      (split-string
                                       (or (getenv-internal "PATH" merged) "")
                                       path-separator t)
                                      (list exec-directory))
                 shell-file-name     (or (getenv-internal "SHELL" merged)
                                         (default-value 'shell-file-name))))
              new-env)))
      (error
       (unless noerror (signal (car err) (cdr err)))))))

;;;###autoload
(defun moyu/reload-env ()
  "Re-capture the login-shell environment and reload it into Emacs."
  (interactive)
  (let ((env-file (moyu/cache-it "env")))
    (generate-env-file env-file)
    (load-env-file env-file)
    (message "env-ext: environment reloaded (%d vars, shell: %s)"
             (length process-environment)
             shell-file-name)))

;;;; ── Tests ───────────────────────────────────────────────────────────────
;; Run:  emacs -q --batch -l lisp/env-ext.el --eval "(ert-run-tests-batch-and-exit)"

(with-eval-after-load 'ert

  ;; Helper: save and restore globals mutated by load-env-file.
  (defmacro env-test--save-globals (&rest body)
    (declare (indent 0))
    `(let ((s-env   (default-value 'process-environment))
           (s-exec  exec-path)
           (s-shell shell-file-name))
       (unwind-protect (progn ,@body)
         (setq-default process-environment s-env
                       exec-path           s-exec
                       shell-file-name     s-shell))))

  ;; Helper: write VARS list to a temp file, bind FILE, run BODY.
  (defmacro env-test--with-temp-file (vars &rest body)
    (declare (indent 1))
    `(let ((file (make-temp-file "env-ext-test-")))
       (unwind-protect
           (progn
             (with-temp-file file (insert (prin1-to-string ,vars)))
             ,@body)
         (ignore-errors (delete-file file)))))

  ;;; moyu/env--denied-p

  (ert-deftest env-ext/denied-p-shell-state ()
    (dolist (v '("HOME" "PWD" "OLDPWD" "SHLVL" "PS1" "TERM" "TERMCAP"
                 "USER" "INSIDE_EMACS"))
      (should (moyu/env--denied-p v))))

  (ert-deftest env-ext/denied-p-display-and-session ()
    (dolist (v '("DISPLAY" "WAYLAND_DISPLAY" "DBUS_SESSION_BUS_ADDRESS"
                 "XAUTHORITY" "WSL_INTEROP"
                 "XDG_CURRENT_DESKTOP" "XDG_RUNTIME_DIR"
                 "XDG_VTNR" "XDG_SEAT" "XDG_SESSION_TYPE" "XDG_SESSION_CLASS"))
      (should (moyu/env--denied-p v))))

  (ert-deftest env-ext/denied-p-sockets ()
    (dolist (v '("I3SOCK" "SWAYSOCK" "GREETD_SOCK" "SEATD_SOCK"))
      (should (moyu/env--denied-p v))))

  (ert-deftest env-ext/denied-p-ssh-gpg ()
    (dolist (v '("SSH_AUTH_SOCK" "SSH_AGENT_PID" "SSH_TTY"
                 "GPG_TTY" "GPG_AGENT_INFO"))
      (should (moyu/env--denied-p v))))

  (ert-deftest env-ext/denied-p-internal-flags ()
    (dolist (v '("DEBUG" "INSECURE" "__CF_USER_TEXT_ENCODING" "__SOME_VAR"))
      (should (moyu/env--denied-p v))))

  (ert-deftest env-ext/denied-p-allows-dev-vars ()
    (dolist (v '("PATH" "GOPATH" "GOROOT" "CARGO_HOME" "RUSTUP_HOME"
                 "NVM_DIR" "JAVA_HOME" "LANG" "EDITOR"
                 "DEEPSEEK_API_KEY" "OPENAI_API_KEY"))
      (should-not (moyu/env--denied-p v))))

  ;;; generate-env-file

  (ert-deftest env-ext/generate-returns-t ()
    (cl-letf (((symbol-function 'moyu/env--shell-environ) (lambda () nil)))
      (let ((tmp (make-temp-file "env-ext-gen-")))
        (unwind-protect (should (eq t (generate-env-file tmp)))
          (ignore-errors (delete-file tmp))))))

  (ert-deftest env-ext/generate-writes-readable-list ()
    (cl-letf (((symbol-function 'moyu/env--shell-environ)
               (lambda () '("PATH=/usr/bin" "GOPATH=/home/user/go"))))
      (let ((tmp (make-temp-file "env-ext-gen-")))
        (unwind-protect
            (progn
              (generate-env-file tmp)
              (with-temp-buffer
                (insert-file-contents tmp)
                (should (listp (read (current-buffer))))))
          (ignore-errors (delete-file tmp))))))

  (ert-deftest env-ext/generate-excludes-denied-includes-allowed ()
    (cl-letf (((symbol-function 'moyu/env--shell-environ)
               (lambda () '("HOME=/root" "SSH_AUTH_SOCK=/tmp/s.sock"
                            "GOPATH=/home/user/go" "PATH=/usr/bin"))))
      (let ((tmp (make-temp-file "env-ext-gen-")))
        (unwind-protect
            (progn
              (generate-env-file tmp)
              (let ((c (with-temp-buffer (insert-file-contents tmp) (buffer-string))))
                (should-not (string-match-p "\"HOME="         c))
                (should-not (string-match-p "SSH_AUTH_SOCK"   c))
                (should     (string-match-p "GOPATH="         c))
                (should     (string-match-p "PATH="           c))))
          (ignore-errors (delete-file tmp))))))

  ;;; load-env-file

  (ert-deftest env-ext/load-missing-signals-file-error ()
    (should-error (load-env-file "/no/such/path/env-xyz") :type 'file-error))

  (ert-deftest env-ext/load-missing-noerror-returns-nil ()
    (should-not (load-env-file "/no/such/path/env-xyz" 'noerror)))

  (ert-deftest env-ext/load-merges-vars ()
    (env-test--save-globals
      (env-test--with-temp-file '("ENVT_A=aaa" "ENVT_B=bbb")
        (load-env-file file)
        (should (member "ENVT_A=aaa" process-environment))
        (should (member "ENVT_B=bbb" process-environment)))))

  (ert-deftest env-ext/load-overrides-existing-key ()
    (env-test--save-globals
      (setq-default process-environment
                    (cons "ENVT_OVER=old" (default-value 'process-environment)))
      (env-test--with-temp-file '("ENVT_OVER=new")
        (load-env-file file)
        (let ((hits (seq-filter (lambda (e) (string-prefix-p "ENVT_OVER=" e))
                                process-environment)))
          (should (= 1 (length hits)))
          (should (equal (car hits) "ENVT_OVER=new"))))))

  (ert-deftest env-ext/load-no-duplicates-on-reload ()
    (env-test--save-globals
      (env-test--with-temp-file '("ENVT_DUP=v")
        (load-env-file file)
        (load-env-file file)
        (should (= 1 (length (seq-filter (lambda (e) (string-prefix-p "ENVT_DUP=" e))
                                         process-environment)))))))

  (ert-deftest env-ext/load-updates-exec-path ()
    (env-test--save-globals
      (env-test--with-temp-file '("PATH=/envtest/bin:/usr/bin")
        (load-env-file file)
        (should (member "/envtest/bin" exec-path)))))

  (ert-deftest env-ext/load-updates-shell-file-name ()
    (env-test--save-globals
      (env-test--with-temp-file '("SHELL=/envtest/sh" "PATH=/usr/bin")
        (load-env-file file)
        (should (equal shell-file-name "/envtest/sh")))))

  (ert-deftest env-ext/load-returns-list ()
    (env-test--save-globals
      (env-test--with-temp-file '("ENVT_R1=x" "ENVT_R2=y")
        (let ((r (load-env-file file)))
          (should (listp r))
          (should (member "ENVT_R1=x" r))
          (should (member "ENVT_R2=y" r))))))

  (ert-deftest env-ext/load-malformed-noerror ()
    (let ((tmp (make-temp-file "env-ext-bad-")))
      (unwind-protect
          (progn
            (with-temp-file tmp (insert "((not valid lisp"))
            (should-not (load-env-file tmp 'noerror)))
        (ignore-errors (delete-file tmp))))))

(provide 'env-ext)
;;; env-ext.el ends here
